### ISSUE TITLE
Environmental Setup Issues

### ISSUE THREAD

**Issue by leopardcat5299** [telematics-lab/IoD_Sim#20]
Hello! 
I am a student who has just studied ns-3 and I am interested in your project.
When I try to build this environment, following the instructions on the github, I have encountered some problems:
1. When I execute "./tools/prepare-ns3.sh" ,the command line asks me to enter "file to patch" many time,how do I type?
![image](https://github.com/telematics-lab/IoD_Sim/assets/96721995/7e0fe57e-89f8-492d-86ea-75e39c2d71fc)

2. When I execute "./ns3 configure --build-profile=debug --enable-examples --disable-mpi --disable-python --enable-modules=iodsim", the command line prints "bash ./ns3 : No such file or directory",it caused the subsequent steps to be unable to execute.
![image](https://github.com/telematics-lab/IoD_Sim/assets/96721995/baf5133a-c15b-4848-98d3-a6bfedae79e8)

Could you please help me solve these problems? 
Thanks in advance.

**Comment by GiovanniGrieco** [comment]
Hi @leopardcat5299, sorry for the delay. I've just patched the `README.md` file with, hopefully, more information on how to get through the setup stage. If you still face issues on using this software, please reply here or open a new issue. Thank you!
