### ISSUE TITLE
RSSI and throughput

### ISSUE THREAD

**Issue by eltonvivot** [telematics-lab/IoD_Sim#6]
Hello,

In [this article ](https://arxiv.org/abs/2203.13710) there are two images with the RSSI (Received Signal Strength Indicator) and Drone's throughput metrics over the time. How do I get them? Is there any way I can receive this metric along with the telemetry data?

Best, 
Elton.

**Comment by GiovanniGrieco** [comment]
Hi Elton,

first of all, thanks for reaching out and sorry for such long waiting with no answers. I'll try my best to be more interactive here in the Issues section in the upcoming future.

As for Fig. 15, the Wi-Fi RSSI can be extracted from the `summary.xml` file if you have any drone with a Wi-Fi network device. As for the LTE Throughput shown in Fig. 17, you need to calculate it indirectly by looking up the amount of data that you have correctly received (indicated in PCAP files). Furthermore, the ZSP (eNB/Cell ID) of reference can be extracted by taking a look at log files such as `lte-0-RlcDlStats.txt`. Drone (UEs) IMSI follow the same order of drones declared in the JSON configuration file.

Best regards,
Giovanni

**Comment by eltonvivot** [comment]
Hi Giovanni,

Sorry for the delayed response. I've been busy with a paper deadline, and I forgot to check the issue. 

Thank you so much, I will follow your guidance to get the metrics. =D

Best regards,
Elton.
